### ISSUE TITLE
ReferenceError: thd is not defined

### ISSUE THREAD

**Issue by himiklab** [openpsa/grid.js#28]
Does not work filterToolbar, gives an error:
```
ReferenceError: thd is not defined
...),a("span.ui-search-input",p).append(u),a(thd).append(p),a.jgrid.bindEv.call(c,u...
```

**Comment by meh-uk** [comment]
Do you have an example demo which shows this problem?

**Comment by himiklab** [comment]
Filter toolbar is not displayed without any errors. jQgrid 4.7 work good.
```
<table id='jqGrid-w1'></table>
<div id='jqGrid-pager-w1'></div>
```
```
jQuery("#jqGrid-w1").jqGrid({
    "url": "admin/jqgrid?action=request",
    "datatype": "json",
    "mtype": "POST",
    "pager": "#jqGrid-pager-w1",
    "colNames": [
        "language",
        "title"
    ],
    "colModel": [
        {
            "name": "language",
            "index": "language",
            "editable": false
        },
        {
            "name": "title",
            "index": "title",
            "editable": false
        }
    ],
    "rowNum": 5,
    "autowidth": true,
    "height": "auto",
    "multiSort": true
})
.navGrid('#jqGrid-pager-w1', {
    "edit": true,
    "add": true,
    "del": true,
    "search": true,
    "view": false
},
{
    "url": "admin/jqgrid?action=edit"
},
{
    "url": "admin/jqgrid?action=add"
},
{
    "url": "admin/jqgrid?action=del"
},
[],
{})
.filterToolbar({
    "stringResult": true
})
```

**Comment by meh-uk** [comment]
Brilliant :). I'll take a look next week unless someone beats me to it!

**Comment by bouks** [comment]
Maybe my changes may have not be re-applied well after the folders revert, since i had remove thd.

**Comment by OlegKi** [comment]
Sorry @himiklab , but are you sure that you really uses jqGrid 4.7? If you would open `jquery.jqGrid.min.js` and would search for `"span.ui-search-input"` or for `(thd` you will don't find and match. So please specify the version which you use more exactly it it's possible.

I suspect that you use the current version of jqGrid from `https://github.com/openpsa/grid.js`. [The line](https://github.com/openpsa/grid.js/blob/master/js/grid.custom.js#L506) contains the reference to undefined variable. It's the bug in [the commit](https://github.com/openpsa/grid.js/commit/c628155f6c29de67c2cdafc15b7302fdeb3f6177#diff-b00cd3167597a03d096b6f2a33e604b7). The `$(thd)` should be probably fixed to `$(th)`. (One should take in the consideration that the link to [the line](https://github.com/openpsa/grid.js/blob/master/js/grid.custom.js#L506) which I included above can be point to another line after the code will be modified).

Best regards
Oleg

**Comment by himiklab** [comment]
Yes, i use current version `grid.js-4.7.0.min.js` from `https://github.com/openpsa/grid.js`.

Thanks!

**Comment by flack** [comment]
It seems I overlooked one line when I re-applied the search toolbar patch. Should be fixed now.

**Comment by flack** [comment]
P.S.: It would be cool to turn the code sample above into a unit test (basic smoketest, just see that no error is thrown)

**Comment by himiklab** [comment]
In last release. Error disappeared, but the panel does not appear.

**Comment by bouks** [comment]
It's a css bug. Necessary css has not been applied.
I do a fix quickly.

**Comment by bouks** [comment]
Fixed in pull request :

https://github.com/openpsa/grid.js/pull/40

commit :

https://github.com/bouks/grid.js/commit/21f3592afaae100abb09d4c1f361149ae489b380

**Comment by meh-uk** [comment]
Pull accepted, I guess this can be closed now.

**Comment by himiklab** [comment]
Better, but still not working.

```html
<div class="ui-search-box">
    <span class="ui-search-input" style="display: none;">
        <input id="gs_language" type="text" value="" name="language">
     </span>
     <span class="ui-search-clear">
         <a class="clearsearchclass" title="Clear Search Value">x</a>
     </span>
</div>
```
Problem in `style="display: none;"`.

**Comment by bouks** [comment]
No. That's because i didn't push the min dist css, i only pushed the less file. I'll do it quickly.

Sorry.

**Comment by meh-uk** [comment]
@bouks I don't think that's the issue. I've created a demo on my machine and I can reproduce the problem.

**Comment by bouks** [comment]
@meh-uk have you used the modified css in the less file ?

It works on my tables.

**Comment by meh-uk** [comment]
Yeah its with the latest code.

**Comment by bouks** [comment]
@meh-uk  I've send you by email my css file after lessc. Test with it.

It works perfect in my projects. FF, IE11 and Chrome tested

**Comment by bouks** [comment]
Be aware of your navigator's cache. :)

**Comment by meh-uk** [comment]
It is definitely still a problem! Perhaps you use search operators, if you do then it will work.

**Comment by bouks** [comment]
What do you mean by "Perhaps you use search operators" ?

**Comment by meh-uk** [comment]
If the searchOperator option is set to true, then it would all display as you'd expect.

**Comment by meh-uk** [comment]
Its now fixed in 05f14469e3a068e1c9ee044d1cde611ec1a99852

**Comment by meh-uk** [comment]
@himiklab let me know if you have any more problems :).

**Comment by bouks** [comment]
I just fixed the bug and see you do.Thanks. :)

**Comment by himiklab** [comment]
Thanks!

But another question. :) In the original jqgrid width of the search field was the same as the width of the column, it is now fixed.

**Comment by meh-uk** [comment]
Can you file a new issue please?
